-- TripNest upgrade 3: hotel details motham database lo (11 kotha tables). OKKA SARI matrame run cheyandi.
USE tripnest;

ALTER TABLE hotels
  ADD COLUMN location VARCHAR(150), ADD COLUMN address VARCHAR(255), ADD COLUMN description TEXT,
  ADD COLUMN latitude DECIMAL(9,6), ADD COLUMN longitude DECIMAL(9,6),
  ADD COLUMN video_url VARCHAR(500), ADD COLUMN panorama_url VARCHAR(500);

-- sample reviews ki user lekunda reviewer_name pettadam kosam
ALTER TABLE reviews MODIFY user_id INT NULL, ADD COLUMN reviewer_name VARCHAR(100), ADD COLUMN helpful INT NOT NULL DEFAULT 0;

CREATE TABLE hotel_images (image_id INT AUTO_INCREMENT PRIMARY KEY, hotel_id INT NOT NULL, url VARCHAR(500) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (hotel_id) REFERENCES hotels(hotel_id) ON DELETE CASCADE);
CREATE TABLE hotel_badges (hotel_id INT NOT NULL, badge VARCHAR(40) NOT NULL, sort_order INT NOT NULL DEFAULT 0, PRIMARY KEY (hotel_id, badge),
  FOREIGN KEY (hotel_id) REFERENCES hotels(hotel_id) ON DELETE CASCADE);
CREATE TABLE amenities (amenity_id INT AUTO_INCREMENT PRIMARY KEY, code VARCHAR(30) NOT NULL, label VARCHAR(60) NOT NULL UNIQUE);
CREATE TABLE hotel_amenities (hotel_id INT NOT NULL, amenity_id INT NOT NULL, sort_order INT NOT NULL DEFAULT 0, PRIMARY KEY (hotel_id, amenity_id),
  FOREIGN KEY (hotel_id) REFERENCES hotels(hotel_id) ON DELETE CASCADE, FOREIGN KEY (amenity_id) REFERENCES amenities(amenity_id) ON DELETE CASCADE);
CREATE TABLE rooms (room_id INT PRIMARY KEY, hotel_id INT NOT NULL, name VARCHAR(100) NOT NULL, size_label VARCHAR(20), capacity_label VARCHAR(30), bed VARCHAR(60),
  price DECIMAL(10,2) NOT NULL, cancellation VARCHAR(120), sort_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (hotel_id) REFERENCES hotels(hotel_id) ON DELETE CASCADE);
CREATE TABLE room_features (room_id INT NOT NULL, feature VARCHAR(60) NOT NULL, sort_order INT NOT NULL DEFAULT 0, PRIMARY KEY (room_id, feature),
  FOREIGN KEY (room_id) REFERENCES rooms(room_id) ON DELETE CASCADE);
CREATE TABLE room_images (image_id INT AUTO_INCREMENT PRIMARY KEY, room_id INT NOT NULL, url VARCHAR(500) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (room_id) REFERENCES rooms(room_id) ON DELETE CASCADE);
CREATE TABLE hotel_policies (policy_id INT AUTO_INCREMENT PRIMARY KEY, hotel_id INT NOT NULL, label VARCHAR(40) NOT NULL, policy_value VARCHAR(80) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (hotel_id) REFERENCES hotels(hotel_id) ON DELETE CASCADE);
CREATE TABLE hotel_rules (rule_id INT AUTO_INCREMENT PRIMARY KEY, hotel_id INT NOT NULL, rule_text VARCHAR(200) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (hotel_id) REFERENCES hotels(hotel_id) ON DELETE CASCADE);
CREATE TABLE hotel_attractions (attraction_id INT AUTO_INCREMENT PRIMARY KEY, hotel_id INT NOT NULL, icon VARCHAR(30) NOT NULL, name VARCHAR(100) NOT NULL, distance VARCHAR(30) NOT NULL, sort_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (hotel_id) REFERENCES hotels(hotel_id) ON DELETE CASCADE);
CREATE TABLE hotel_faqs (faq_id INT AUTO_INCREMENT PRIMARY KEY, hotel_id INT NOT NULL, question VARCHAR(200) NOT NULL, answer TEXT NOT NULL, sort_order INT NOT NULL DEFAULT 0,
  FOREIGN KEY (hotel_id) REFERENCES hotels(hotel_id) ON DELETE CASCADE);

INSERT INTO amenities (code, label) VALUES
('wifi', 'Free Wi-Fi'),
('pool', 'Swimming Pool'),
('spa', 'Spa & Wellness'),
('restaurant', 'Restaurant & Bar'),
('gym', 'Fitness Centre'),
('parking', 'Free Parking');

-- ===== Hotel 1: Azure Cliff Resort =====
UPDATE hotels SET location = 'Oia, Santorini, Greece', address = 'Oia, Santorini, Greece — guest entrance on main road', description = 'Azure Cliff Resort offers a memorable stay in Oia, Santorini, Greece, with comfortable rooms, friendly service and easy access to the best local sights.', latitude = 36.4618, longitude = 25.3753, video_url = 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4', panorama_url = 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=2400&q=80' WHERE hotel_id = 1;
INSERT INTO hotel_images (hotel_id, url, sort_order) VALUES (1, 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80', 0), (1, 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80', 1), (1, 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=900&q=80', 2), (1, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80', 3);
INSERT INTO hotel_badges (hotel_id, badge, sort_order) VALUES (1, 'Cliffside', 0), (1, 'Infinity Pool', 1), (1, 'Top Rated', 2);
INSERT INTO hotel_amenities (hotel_id, amenity_id, sort_order) VALUES (1, (SELECT amenity_id FROM amenities WHERE label = 'Free Wi-Fi'), 0), (1, (SELECT amenity_id FROM amenities WHERE label = 'Swimming Pool'), 1), (1, (SELECT amenity_id FROM amenities WHERE label = 'Spa & Wellness'), 2), (1, (SELECT amenity_id FROM amenities WHERE label = 'Restaurant & Bar'), 3), (1, (SELECT amenity_id FROM amenities WHERE label = 'Fitness Centre'), 4), (1, (SELECT amenity_id FROM amenities WHERE label = 'Free Parking'), 5);
INSERT INTO rooms (room_id, hotel_id, name, size_label, capacity_label, bed, price, cancellation, sort_order) VALUES (11, 1, 'Deluxe Room', '32 m²', '2 guests', '1 King bed', 310, 'Free cancellation until 48h before', 0);
INSERT INTO room_features (room_id, feature, sort_order) VALUES (11, 'Free Wi-Fi', 0), (11, 'Air conditioning', 1), (11, 'Breakfast option', 2);
INSERT INTO room_images (room_id, url, sort_order) VALUES (11, 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80', 0), (11, 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80', 1);
INSERT INTO rooms (room_id, hotel_id, name, size_label, capacity_label, bed, price, cancellation, sort_order) VALUES (12, 1, 'Premium Suite', '48 m²', '3 guests', '1 King + Sofa bed', 496, 'Free cancellation until 72h before', 1);
INSERT INTO room_features (room_id, feature, sort_order) VALUES (12, 'Free Wi-Fi', 0), (12, 'Air conditioning', 1), (12, 'Breakfast option', 2);
INSERT INTO room_images (room_id, url, sort_order) VALUES (12, 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80', 0), (12, 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=900&q=80', 1);
INSERT INTO rooms (room_id, hotel_id, name, size_label, capacity_label, bed, price, cancellation, sort_order) VALUES (13, 1, 'Family Villa', '70 m²', '5 guests', '2 Queen beds', 682, 'Non-refundable', 2);
INSERT INTO room_features (room_id, feature, sort_order) VALUES (13, 'Free Wi-Fi', 0), (13, 'Air conditioning', 1), (13, 'Breakfast option', 2);
INSERT INTO room_images (room_id, url, sort_order) VALUES (13, 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=900&q=80', 0), (13, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80', 1);
INSERT INTO hotel_policies (hotel_id, label, policy_value, sort_order) VALUES (1, 'Check-in', '2:00 PM', 0), (1, 'Check-out', '11:00 AM', 1), (1, 'Pets', 'On request', 2);
INSERT INTO hotel_rules (hotel_id, rule_text, sort_order) VALUES (1, 'No smoking inside rooms', 0), (1, 'Quiet hours 10 PM – 7 AM', 1), (1, 'Valid photo ID required at check-in', 2);
INSERT INTO hotel_attractions (hotel_id, icon, name, distance, sort_order) VALUES (1, 'pin', 'City Centre', '1.2 km', 0), (1, 'beach', 'Main Viewpoint', '2.5 km', 1), (1, 'airport', 'Nearest Airport', '18 km', 2);
INSERT INTO hotel_faqs (hotel_id, question, answer, sort_order) VALUES (1, 'Is breakfast included?', 'Breakfast is available and can be added to any room at booking.', 0), (1, 'Is airport pickup available?', 'Yes, airport transfers can be arranged on request for an extra charge.', 1), (1, 'Can I cancel my booking?', 'Most rooms allow free cancellation. Check the policy shown on each room.', 2);
INSERT INTO reviews (user_id, hotel_id, rating, comment, reviewer_name, helpful, created_at) VALUES (NULL, 1, 5, 'Stunning stay. Staff went out of their way and the views were unreal.', 'Ananya R.', 3, DATE_SUB(NOW(), INTERVAL 1 MONTH)), (NULL, 1, 5, 'Spotless rooms, great breakfast and a perfect location.', 'Michael T.', 5, DATE_SUB(NOW(), INTERVAL 2 MONTH)), (NULL, 1, 4, 'Lovely hotel overall. Check-in was slow but everything else was great.', 'Sofia L.', 7, DATE_SUB(NOW(), INTERVAL 3 MONTH)), (NULL, 1, 4, 'Good value for money and very comfortable beds.', 'Rahul K.', 9, DATE_SUB(NOW(), INTERVAL 4 MONTH)), (NULL, 1, 5, 'One of the best hotels we have stayed at. Will be back.', 'Emma W.', 11, DATE_SUB(NOW(), INTERVAL 5 MONTH)), (NULL, 1, 3, 'Nice property but a bit noisy in the evenings.', 'David P.', 13, DATE_SUB(NOW(), INTERVAL 6 MONTH));

-- ===== Hotel 2: The Nest Boutique Hotel =====
UPDATE hotels SET location = 'Trastevere, Rome, Italy', address = 'Trastevere, Rome, Italy — guest entrance on main road', description = 'The Nest Boutique Hotel offers a memorable stay in Trastevere, Rome, Italy, with comfortable rooms, friendly service and easy access to the best local sights.', latitude = 41.8894, longitude = 12.47, video_url = 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4', panorama_url = 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=2400&q=80' WHERE hotel_id = 2;
INSERT INTO hotel_images (hotel_id, url, sort_order) VALUES (2, 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=900&q=80', 0), (2, 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80', 1), (2, 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80', 2), (2, 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=900&q=80', 3);
INSERT INTO hotel_badges (hotel_id, badge, sort_order) VALUES (2, 'Boutique', 0), (2, 'City Centre', 1);
INSERT INTO hotel_amenities (hotel_id, amenity_id, sort_order) VALUES (2, (SELECT amenity_id FROM amenities WHERE label = 'Free Wi-Fi'), 0), (2, (SELECT amenity_id FROM amenities WHERE label = 'Swimming Pool'), 1), (2, (SELECT amenity_id FROM amenities WHERE label = 'Spa & Wellness'), 2), (2, (SELECT amenity_id FROM amenities WHERE label = 'Restaurant & Bar'), 3), (2, (SELECT amenity_id FROM amenities WHERE label = 'Fitness Centre'), 4), (2, (SELECT amenity_id FROM amenities WHERE label = 'Free Parking'), 5);
INSERT INTO rooms (room_id, hotel_id, name, size_label, capacity_label, bed, price, cancellation, sort_order) VALUES (21, 2, 'Deluxe Room', '32 m²', '2 guests', '1 King bed', 190, 'Free cancellation until 48h before', 0);
INSERT INTO room_features (room_id, feature, sort_order) VALUES (21, 'Free Wi-Fi', 0), (21, 'Air conditioning', 1), (21, 'Breakfast option', 2);
INSERT INTO room_images (room_id, url, sort_order) VALUES (21, 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=900&q=80', 0), (21, 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80', 1);
INSERT INTO rooms (room_id, hotel_id, name, size_label, capacity_label, bed, price, cancellation, sort_order) VALUES (22, 2, 'Premium Suite', '48 m²', '3 guests', '1 King + Sofa bed', 304, 'Free cancellation until 72h before', 1);
INSERT INTO room_features (room_id, feature, sort_order) VALUES (22, 'Free Wi-Fi', 0), (22, 'Air conditioning', 1), (22, 'Breakfast option', 2);
INSERT INTO room_images (room_id, url, sort_order) VALUES (22, 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80', 0), (22, 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80', 1);
INSERT INTO rooms (room_id, hotel_id, name, size_label, capacity_label, bed, price, cancellation, sort_order) VALUES (23, 2, 'Family Villa', '70 m²', '5 guests', '2 Queen beds', 418, 'Non-refundable', 2);
INSERT INTO room_features (room_id, feature, sort_order) VALUES (23, 'Free Wi-Fi', 0), (23, 'Air conditioning', 1), (23, 'Breakfast option', 2);
INSERT INTO room_images (room_id, url, sort_order) VALUES (23, 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80', 0), (23, 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=900&q=80', 1);
INSERT INTO hotel_policies (hotel_id, label, policy_value, sort_order) VALUES (2, 'Check-in', '2:00 PM', 0), (2, 'Check-out', '11:00 AM', 1), (2, 'Pets', 'On request', 2);
INSERT INTO hotel_rules (hotel_id, rule_text, sort_order) VALUES (2, 'No smoking inside rooms', 0), (2, 'Quiet hours 10 PM – 7 AM', 1), (2, 'Valid photo ID required at check-in', 2);
INSERT INTO hotel_attractions (hotel_id, icon, name, distance, sort_order) VALUES (2, 'pin', 'City Centre', '1.2 km', 0), (2, 'beach', 'Main Viewpoint', '2.5 km', 1), (2, 'airport', 'Nearest Airport', '18 km', 2);
INSERT INTO hotel_faqs (hotel_id, question, answer, sort_order) VALUES (2, 'Is breakfast included?', 'Breakfast is available and can be added to any room at booking.', 0), (2, 'Is airport pickup available?', 'Yes, airport transfers can be arranged on request for an extra charge.', 1), (2, 'Can I cancel my booking?', 'Most rooms allow free cancellation. Check the policy shown on each room.', 2);
INSERT INTO reviews (user_id, hotel_id, rating, comment, reviewer_name, helpful, created_at) VALUES (NULL, 2, 5, 'Stunning stay. Staff went out of their way and the views were unreal.', 'Ananya R.', 3, DATE_SUB(NOW(), INTERVAL 1 MONTH)), (NULL, 2, 5, 'Spotless rooms, great breakfast and a perfect location.', 'Michael T.', 5, DATE_SUB(NOW(), INTERVAL 2 MONTH)), (NULL, 2, 4, 'Lovely hotel overall. Check-in was slow but everything else was great.', 'Sofia L.', 7, DATE_SUB(NOW(), INTERVAL 3 MONTH)), (NULL, 2, 4, 'Good value for money and very comfortable beds.', 'Rahul K.', 9, DATE_SUB(NOW(), INTERVAL 4 MONTH)), (NULL, 2, 5, 'One of the best hotels we have stayed at. Will be back.', 'Emma W.', 11, DATE_SUB(NOW(), INTERVAL 5 MONTH)), (NULL, 2, 3, 'Nice property but a bit noisy in the evenings.', 'David P.', 13, DATE_SUB(NOW(), INTERVAL 6 MONTH));

-- ===== Hotel 3: Harbor View Suites =====
UPDATE hotels SET location = 'Le Marais, Paris, France', address = 'Le Marais, Paris, France — guest entrance on main road', description = 'Harbor View Suites offers a memorable stay in Le Marais, Paris, France, with comfortable rooms, friendly service and easy access to the best local sights.', latitude = 48.8566, longitude = 2.3522, video_url = 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4', panorama_url = 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=2400&q=80' WHERE hotel_id = 3;
INSERT INTO hotel_images (hotel_id, url, sort_order) VALUES (3, 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=900&q=80', 0), (3, 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80', 1), (3, 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80', 2), (3, 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=900&q=80', 3);
INSERT INTO hotel_badges (hotel_id, badge, sort_order) VALUES (3, 'Suites', 0), (3, 'Romantic', 1);
INSERT INTO hotel_amenities (hotel_id, amenity_id, sort_order) VALUES (3, (SELECT amenity_id FROM amenities WHERE label = 'Free Wi-Fi'), 0), (3, (SELECT amenity_id FROM amenities WHERE label = 'Swimming Pool'), 1), (3, (SELECT amenity_id FROM amenities WHERE label = 'Spa & Wellness'), 2), (3, (SELECT amenity_id FROM amenities WHERE label = 'Restaurant & Bar'), 3), (3, (SELECT amenity_id FROM amenities WHERE label = 'Fitness Centre'), 4), (3, (SELECT amenity_id FROM amenities WHERE label = 'Free Parking'), 5);
INSERT INTO rooms (room_id, hotel_id, name, size_label, capacity_label, bed, price, cancellation, sort_order) VALUES (31, 3, 'Deluxe Room', '32 m²', '2 guests', '1 King bed', 245, 'Free cancellation until 48h before', 0);
INSERT INTO room_features (room_id, feature, sort_order) VALUES (31, 'Free Wi-Fi', 0), (31, 'Air conditioning', 1), (31, 'Breakfast option', 2);
INSERT INTO room_images (room_id, url, sort_order) VALUES (31, 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=900&q=80', 0), (31, 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80', 1);
INSERT INTO rooms (room_id, hotel_id, name, size_label, capacity_label, bed, price, cancellation, sort_order) VALUES (32, 3, 'Premium Suite', '48 m²', '3 guests', '1 King + Sofa bed', 392, 'Free cancellation until 72h before', 1);
INSERT INTO room_features (room_id, feature, sort_order) VALUES (32, 'Free Wi-Fi', 0), (32, 'Air conditioning', 1), (32, 'Breakfast option', 2);
INSERT INTO room_images (room_id, url, sort_order) VALUES (32, 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80', 0), (32, 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80', 1);
INSERT INTO rooms (room_id, hotel_id, name, size_label, capacity_label, bed, price, cancellation, sort_order) VALUES (33, 3, 'Family Villa', '70 m²', '5 guests', '2 Queen beds', 539, 'Non-refundable', 2);
INSERT INTO room_features (room_id, feature, sort_order) VALUES (33, 'Free Wi-Fi', 0), (33, 'Air conditioning', 1), (33, 'Breakfast option', 2);
INSERT INTO room_images (room_id, url, sort_order) VALUES (33, 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80', 0), (33, 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=900&q=80', 1);
INSERT INTO hotel_policies (hotel_id, label, policy_value, sort_order) VALUES (3, 'Check-in', '2:00 PM', 0), (3, 'Check-out', '11:00 AM', 1), (3, 'Pets', 'On request', 2);
INSERT INTO hotel_rules (hotel_id, rule_text, sort_order) VALUES (3, 'No smoking inside rooms', 0), (3, 'Quiet hours 10 PM – 7 AM', 1), (3, 'Valid photo ID required at check-in', 2);
INSERT INTO hotel_attractions (hotel_id, icon, name, distance, sort_order) VALUES (3, 'pin', 'City Centre', '1.2 km', 0), (3, 'beach', 'Main Viewpoint', '2.5 km', 1), (3, 'airport', 'Nearest Airport', '18 km', 2);
INSERT INTO hotel_faqs (hotel_id, question, answer, sort_order) VALUES (3, 'Is breakfast included?', 'Breakfast is available and can be added to any room at booking.', 0), (3, 'Is airport pickup available?', 'Yes, airport transfers can be arranged on request for an extra charge.', 1), (3, 'Can I cancel my booking?', 'Most rooms allow free cancellation. Check the policy shown on each room.', 2);
INSERT INTO reviews (user_id, hotel_id, rating, comment, reviewer_name, helpful, created_at) VALUES (NULL, 3, 5, 'Stunning stay. Staff went out of their way and the views were unreal.', 'Ananya R.', 3, DATE_SUB(NOW(), INTERVAL 1 MONTH)), (NULL, 3, 5, 'Spotless rooms, great breakfast and a perfect location.', 'Michael T.', 5, DATE_SUB(NOW(), INTERVAL 2 MONTH)), (NULL, 3, 4, 'Lovely hotel overall. Check-in was slow but everything else was great.', 'Sofia L.', 7, DATE_SUB(NOW(), INTERVAL 3 MONTH)), (NULL, 3, 4, 'Good value for money and very comfortable beds.', 'Rahul K.', 9, DATE_SUB(NOW(), INTERVAL 4 MONTH)), (NULL, 3, 5, 'One of the best hotels we have stayed at. Will be back.', 'Emma W.', 11, DATE_SUB(NOW(), INTERVAL 5 MONTH)), (NULL, 3, 3, 'Nice property but a bit noisy in the evenings.', 'David P.', 13, DATE_SUB(NOW(), INTERVAL 6 MONTH));

-- ===== Hotel 4: Alpine Summit Lodge =====
UPDATE hotels SET location = 'Zermatt, Switzerland', address = 'Zermatt, Switzerland — guest entrance on main road', description = 'Alpine Summit Lodge offers a memorable stay in Zermatt, Switzerland, with comfortable rooms, friendly service and easy access to the best local sights.', latitude = 46.0207, longitude = 7.7491, video_url = 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4', panorama_url = 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=2400&q=80' WHERE hotel_id = 4;
INSERT INTO hotel_images (hotel_id, url, sort_order) VALUES (4, 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80', 0), (4, 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80', 1), (4, 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=900&q=80', 2), (4, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80', 3);
INSERT INTO hotel_badges (hotel_id, badge, sort_order) VALUES (4, 'Ski-in Ski-out', 0), (4, 'Mountain View', 1);
INSERT INTO hotel_amenities (hotel_id, amenity_id, sort_order) VALUES (4, (SELECT amenity_id FROM amenities WHERE label = 'Free Wi-Fi'), 0), (4, (SELECT amenity_id FROM amenities WHERE label = 'Swimming Pool'), 1), (4, (SELECT amenity_id FROM amenities WHERE label = 'Spa & Wellness'), 2), (4, (SELECT amenity_id FROM amenities WHERE label = 'Restaurant & Bar'), 3), (4, (SELECT amenity_id FROM amenities WHERE label = 'Fitness Centre'), 4), (4, (SELECT amenity_id FROM amenities WHERE label = 'Free Parking'), 5);
INSERT INTO rooms (room_id, hotel_id, name, size_label, capacity_label, bed, price, cancellation, sort_order) VALUES (41, 4, 'Deluxe Room', '32 m²', '2 guests', '1 King bed', 260, 'Free cancellation until 48h before', 0);
INSERT INTO room_features (room_id, feature, sort_order) VALUES (41, 'Free Wi-Fi', 0), (41, 'Air conditioning', 1), (41, 'Breakfast option', 2);
INSERT INTO room_images (room_id, url, sort_order) VALUES (41, 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80', 0), (41, 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80', 1);
INSERT INTO rooms (room_id, hotel_id, name, size_label, capacity_label, bed, price, cancellation, sort_order) VALUES (42, 4, 'Premium Suite', '48 m²', '3 guests', '1 King + Sofa bed', 416, 'Free cancellation until 72h before', 1);
INSERT INTO room_features (room_id, feature, sort_order) VALUES (42, 'Free Wi-Fi', 0), (42, 'Air conditioning', 1), (42, 'Breakfast option', 2);
INSERT INTO room_images (room_id, url, sort_order) VALUES (42, 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80', 0), (42, 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=900&q=80', 1);
INSERT INTO rooms (room_id, hotel_id, name, size_label, capacity_label, bed, price, cancellation, sort_order) VALUES (43, 4, 'Family Villa', '70 m²', '5 guests', '2 Queen beds', 572, 'Non-refundable', 2);
INSERT INTO room_features (room_id, feature, sort_order) VALUES (43, 'Free Wi-Fi', 0), (43, 'Air conditioning', 1), (43, 'Breakfast option', 2);
INSERT INTO room_images (room_id, url, sort_order) VALUES (43, 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=900&q=80', 0), (43, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80', 1);
INSERT INTO hotel_policies (hotel_id, label, policy_value, sort_order) VALUES (4, 'Check-in', '2:00 PM', 0), (4, 'Check-out', '11:00 AM', 1), (4, 'Pets', 'On request', 2);
INSERT INTO hotel_rules (hotel_id, rule_text, sort_order) VALUES (4, 'No smoking inside rooms', 0), (4, 'Quiet hours 10 PM – 7 AM', 1), (4, 'Valid photo ID required at check-in', 2);
INSERT INTO hotel_attractions (hotel_id, icon, name, distance, sort_order) VALUES (4, 'pin', 'City Centre', '1.2 km', 0), (4, 'beach', 'Main Viewpoint', '2.5 km', 1), (4, 'airport', 'Nearest Airport', '18 km', 2);
INSERT INTO hotel_faqs (hotel_id, question, answer, sort_order) VALUES (4, 'Is breakfast included?', 'Breakfast is available and can be added to any room at booking.', 0), (4, 'Is airport pickup available?', 'Yes, airport transfers can be arranged on request for an extra charge.', 1), (4, 'Can I cancel my booking?', 'Most rooms allow free cancellation. Check the policy shown on each room.', 2);
INSERT INTO reviews (user_id, hotel_id, rating, comment, reviewer_name, helpful, created_at) VALUES (NULL, 4, 5, 'Stunning stay. Staff went out of their way and the views were unreal.', 'Ananya R.', 3, DATE_SUB(NOW(), INTERVAL 1 MONTH)), (NULL, 4, 5, 'Spotless rooms, great breakfast and a perfect location.', 'Michael T.', 5, DATE_SUB(NOW(), INTERVAL 2 MONTH)), (NULL, 4, 4, 'Lovely hotel overall. Check-in was slow but everything else was great.', 'Sofia L.', 7, DATE_SUB(NOW(), INTERVAL 3 MONTH)), (NULL, 4, 4, 'Good value for money and very comfortable beds.', 'Rahul K.', 9, DATE_SUB(NOW(), INTERVAL 4 MONTH)), (NULL, 4, 5, 'One of the best hotels we have stayed at. Will be back.', 'Emma W.', 11, DATE_SUB(NOW(), INTERVAL 5 MONTH)), (NULL, 4, 3, 'Nice property but a bit noisy in the evenings.', 'David P.', 13, DATE_SUB(NOW(), INTERVAL 6 MONTH));

-- ===== Hotel 5: Bali Jungle Villas =====
UPDATE hotels SET location = 'Ubud, Bali, Indonesia', address = 'Ubud, Bali, Indonesia — guest entrance on main road', description = 'Bali Jungle Villas offers a memorable stay in Ubud, Bali, Indonesia, with comfortable rooms, friendly service and easy access to the best local sights.', latitude = -8.5069, longitude = 115.2625, video_url = 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4', panorama_url = 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=2400&q=80' WHERE hotel_id = 5;
INSERT INTO hotel_images (hotel_id, url, sort_order) VALUES (5, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80', 0), (5, 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80', 1), (5, 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80', 2), (5, 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=900&q=80', 3);
INSERT INTO hotel_badges (hotel_id, badge, sort_order) VALUES (5, 'Private Pool', 0), (5, 'Wellness', 1);
INSERT INTO hotel_amenities (hotel_id, amenity_id, sort_order) VALUES (5, (SELECT amenity_id FROM amenities WHERE label = 'Free Wi-Fi'), 0), (5, (SELECT amenity_id FROM amenities WHERE label = 'Swimming Pool'), 1), (5, (SELECT amenity_id FROM amenities WHERE label = 'Spa & Wellness'), 2), (5, (SELECT amenity_id FROM amenities WHERE label = 'Restaurant & Bar'), 3), (5, (SELECT amenity_id FROM amenities WHERE label = 'Fitness Centre'), 4), (5, (SELECT amenity_id FROM amenities WHERE label = 'Free Parking'), 5);
INSERT INTO rooms (room_id, hotel_id, name, size_label, capacity_label, bed, price, cancellation, sort_order) VALUES (51, 5, 'Deluxe Room', '32 m²', '2 guests', '1 King bed', 150, 'Free cancellation until 48h before', 0);
INSERT INTO room_features (room_id, feature, sort_order) VALUES (51, 'Free Wi-Fi', 0), (51, 'Air conditioning', 1), (51, 'Breakfast option', 2);
INSERT INTO room_images (room_id, url, sort_order) VALUES (51, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80', 0), (51, 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80', 1);
INSERT INTO rooms (room_id, hotel_id, name, size_label, capacity_label, bed, price, cancellation, sort_order) VALUES (52, 5, 'Premium Suite', '48 m²', '3 guests', '1 King + Sofa bed', 240, 'Free cancellation until 72h before', 1);
INSERT INTO room_features (room_id, feature, sort_order) VALUES (52, 'Free Wi-Fi', 0), (52, 'Air conditioning', 1), (52, 'Breakfast option', 2);
INSERT INTO room_images (room_id, url, sort_order) VALUES (52, 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80', 0), (52, 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80', 1);
INSERT INTO rooms (room_id, hotel_id, name, size_label, capacity_label, bed, price, cancellation, sort_order) VALUES (53, 5, 'Family Villa', '70 m²', '5 guests', '2 Queen beds', 330, 'Non-refundable', 2);
INSERT INTO room_features (room_id, feature, sort_order) VALUES (53, 'Free Wi-Fi', 0), (53, 'Air conditioning', 1), (53, 'Breakfast option', 2);
INSERT INTO room_images (room_id, url, sort_order) VALUES (53, 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80', 0), (53, 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=900&q=80', 1);
INSERT INTO hotel_policies (hotel_id, label, policy_value, sort_order) VALUES (5, 'Check-in', '2:00 PM', 0), (5, 'Check-out', '11:00 AM', 1), (5, 'Pets', 'On request', 2);
INSERT INTO hotel_rules (hotel_id, rule_text, sort_order) VALUES (5, 'No smoking inside rooms', 0), (5, 'Quiet hours 10 PM – 7 AM', 1), (5, 'Valid photo ID required at check-in', 2);
INSERT INTO hotel_attractions (hotel_id, icon, name, distance, sort_order) VALUES (5, 'pin', 'City Centre', '1.2 km', 0), (5, 'beach', 'Main Viewpoint', '2.5 km', 1), (5, 'airport', 'Nearest Airport', '18 km', 2);
INSERT INTO hotel_faqs (hotel_id, question, answer, sort_order) VALUES (5, 'Is breakfast included?', 'Breakfast is available and can be added to any room at booking.', 0), (5, 'Is airport pickup available?', 'Yes, airport transfers can be arranged on request for an extra charge.', 1), (5, 'Can I cancel my booking?', 'Most rooms allow free cancellation. Check the policy shown on each room.', 2);
INSERT INTO reviews (user_id, hotel_id, rating, comment, reviewer_name, helpful, created_at) VALUES (NULL, 5, 5, 'Stunning stay. Staff went out of their way and the views were unreal.', 'Ananya R.', 3, DATE_SUB(NOW(), INTERVAL 1 MONTH)), (NULL, 5, 5, 'Spotless rooms, great breakfast and a perfect location.', 'Michael T.', 5, DATE_SUB(NOW(), INTERVAL 2 MONTH)), (NULL, 5, 4, 'Lovely hotel overall. Check-in was slow but everything else was great.', 'Sofia L.', 7, DATE_SUB(NOW(), INTERVAL 3 MONTH)), (NULL, 5, 4, 'Good value for money and very comfortable beds.', 'Rahul K.', 9, DATE_SUB(NOW(), INTERVAL 4 MONTH)), (NULL, 5, 5, 'One of the best hotels we have stayed at. Will be back.', 'Emma W.', 11, DATE_SUB(NOW(), INTERVAL 5 MONTH)), (NULL, 5, 3, 'Nice property but a bit noisy in the evenings.', 'David P.', 13, DATE_SUB(NOW(), INTERVAL 6 MONTH));

-- ===== Hotel 6: Maldives Coral Retreat =====
UPDATE hotels SET location = 'Baa Atoll, Maldives', address = 'Baa Atoll, Maldives — guest entrance on main road', description = 'Maldives Coral Retreat offers a memorable stay in Baa Atoll, Maldives, with comfortable rooms, friendly service and easy access to the best local sights.', latitude = 5.1667, longitude = 73, video_url = 'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4', panorama_url = 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=2400&q=80' WHERE hotel_id = 6;
INSERT INTO hotel_images (hotel_id, url, sort_order) VALUES (6, 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=900&q=80', 0), (6, 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80', 1), (6, 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80', 2), (6, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80', 3);
INSERT INTO hotel_badges (hotel_id, badge, sort_order) VALUES (6, 'Overwater Villa', 0), (6, 'Luxury', 1);
INSERT INTO hotel_amenities (hotel_id, amenity_id, sort_order) VALUES (6, (SELECT amenity_id FROM amenities WHERE label = 'Free Wi-Fi'), 0), (6, (SELECT amenity_id FROM amenities WHERE label = 'Swimming Pool'), 1), (6, (SELECT amenity_id FROM amenities WHERE label = 'Spa & Wellness'), 2), (6, (SELECT amenity_id FROM amenities WHERE label = 'Restaurant & Bar'), 3), (6, (SELECT amenity_id FROM amenities WHERE label = 'Fitness Centre'), 4), (6, (SELECT amenity_id FROM amenities WHERE label = 'Free Parking'), 5);
INSERT INTO rooms (room_id, hotel_id, name, size_label, capacity_label, bed, price, cancellation, sort_order) VALUES (61, 6, 'Deluxe Room', '32 m²', '2 guests', '1 King bed', 520, 'Free cancellation until 48h before', 0);
INSERT INTO room_features (room_id, feature, sort_order) VALUES (61, 'Free Wi-Fi', 0), (61, 'Air conditioning', 1), (61, 'Breakfast option', 2);
INSERT INTO room_images (room_id, url, sort_order) VALUES (61, 'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=900&q=80', 0), (61, 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80', 1);
INSERT INTO rooms (room_id, hotel_id, name, size_label, capacity_label, bed, price, cancellation, sort_order) VALUES (62, 6, 'Premium Suite', '48 m²', '3 guests', '1 King + Sofa bed', 832, 'Free cancellation until 72h before', 1);
INSERT INTO room_features (room_id, feature, sort_order) VALUES (62, 'Free Wi-Fi', 0), (62, 'Air conditioning', 1), (62, 'Breakfast option', 2);
INSERT INTO room_images (room_id, url, sort_order) VALUES (62, 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=900&q=80', 0), (62, 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80', 1);
INSERT INTO rooms (room_id, hotel_id, name, size_label, capacity_label, bed, price, cancellation, sort_order) VALUES (63, 6, 'Family Villa', '70 m²', '5 guests', '2 Queen beds', 1144, 'Non-refundable', 2);
INSERT INTO room_features (room_id, feature, sort_order) VALUES (63, 'Free Wi-Fi', 0), (63, 'Air conditioning', 1), (63, 'Breakfast option', 2);
INSERT INTO room_images (room_id, url, sort_order) VALUES (63, 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=900&q=80', 0), (63, 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=80', 1);
INSERT INTO hotel_policies (hotel_id, label, policy_value, sort_order) VALUES (6, 'Check-in', '2:00 PM', 0), (6, 'Check-out', '11:00 AM', 1), (6, 'Pets', 'On request', 2);
INSERT INTO hotel_rules (hotel_id, rule_text, sort_order) VALUES (6, 'No smoking inside rooms', 0), (6, 'Quiet hours 10 PM – 7 AM', 1), (6, 'Valid photo ID required at check-in', 2);
INSERT INTO hotel_attractions (hotel_id, icon, name, distance, sort_order) VALUES (6, 'pin', 'City Centre', '1.2 km', 0), (6, 'beach', 'Main Viewpoint', '2.5 km', 1), (6, 'airport', 'Nearest Airport', '18 km', 2);
INSERT INTO hotel_faqs (hotel_id, question, answer, sort_order) VALUES (6, 'Is breakfast included?', 'Breakfast is available and can be added to any room at booking.', 0), (6, 'Is airport pickup available?', 'Yes, airport transfers can be arranged on request for an extra charge.', 1), (6, 'Can I cancel my booking?', 'Most rooms allow free cancellation. Check the policy shown on each room.', 2);
INSERT INTO reviews (user_id, hotel_id, rating, comment, reviewer_name, helpful, created_at) VALUES (NULL, 6, 5, 'Stunning stay. Staff went out of their way and the views were unreal.', 'Ananya R.', 3, DATE_SUB(NOW(), INTERVAL 1 MONTH)), (NULL, 6, 5, 'Spotless rooms, great breakfast and a perfect location.', 'Michael T.', 5, DATE_SUB(NOW(), INTERVAL 2 MONTH)), (NULL, 6, 4, 'Lovely hotel overall. Check-in was slow but everything else was great.', 'Sofia L.', 7, DATE_SUB(NOW(), INTERVAL 3 MONTH)), (NULL, 6, 4, 'Good value for money and very comfortable beds.', 'Rahul K.', 9, DATE_SUB(NOW(), INTERVAL 4 MONTH)), (NULL, 6, 5, 'One of the best hotels we have stayed at. Will be back.', 'Emma W.', 11, DATE_SUB(NOW(), INTERVAL 5 MONTH)), (NULL, 6, 3, 'Nice property but a bit noisy in the evenings.', 'David P.', 13, DATE_SUB(NOW(), INTERVAL 6 MONTH));

SELECT h.name, (SELECT COUNT(*) FROM rooms r WHERE r.hotel_id = h.hotel_id) AS rooms, (SELECT COUNT(*) FROM hotel_images i WHERE i.hotel_id = h.hotel_id) AS images FROM hotels h;
